# Generated by Django 3.1.2 on 2021-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=222)),
                ('email', models.CharField(max_length=222)),
                ('phno', models.CharField(max_length=12)),
                ('msg', models.TextField(max_length=256)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
